[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = ['https://fonts.gstatic.com', 'https://fonts.googleapis.com']

[dev]
  command = "npm run dev"
  targetPort = 8080
  publish = "_site/"

[build]
  publish = "_site/"
  command = "npm run build"
