[[plugins]]
  package = "netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"

[build]
  command = "npm run build"
  publish = ".next"

# Disable asset optimization since Next.js already does this: https://github.com/netlify/netlify-plugin-nextjs#asset-optimization
[build.processing]
  skip_processing = true
