[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Fail build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 1.0
    best-practices = 0.9
    seo = 0.89
    pwa = 0

[dev]
  command = "pnpm run dev"

[build]
  command = "pnpm run build"
  publish = "build"
